// JavaScriptProjects/ReactProjects/warehouse_wars/front-end/ww-react-ts/src/components/chat/ChatEntry.tsx
import { CSSProperties } from "react"

import './ChatEntry.css'



interface ChatEntryProps {
  token: string,
  author: string,
  html: JSX.Element,
  classes: string[],
  style: CSSProperties
}


function ChatEntry({token, author, html, classes, style}: ChatEntryProps) {
  return (
    <div className={["chat-entry", ...classes].join(" ")} style={style}>
      <div className={"chat-entry-metadata"}>
        <p>{"author: "+author}</p>
        <p>{"token: "+token}</p>
      </div>
      {html}
    </div>
  )
}

export default ChatEntry

// JavaScriptProjects/ReactProjects/warehouse_wars/front-end/ww-angular/src/app/components/chat/chat-entry/chat-entry.component.ts
import { Component, Input } from '@angular/core';
import { User } from 'src/app/types/User';

@Component({
  selector: 'chat-entry',
  templateUrl: './chat-entry.component.html',
  styleUrls: ['./chat-entry.component.css']
})
export class ChatEntryComponent {
  @Input() token: string | null = null;
  @Input() author: User | null = null;
  
  @Input() html: string = '';
  @Input() style: string = '';
  @Input() classes: string[] = [];
  
}
