// JavaScriptProjects/ReactProjects/warehouse_wars/front-end/ww-react-ts/src/components/game/Login.tsx
import { SyntheticEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import useWebSocket, { ReadyState } from "react-use-websocket";
import { useDispatch, useSelector } from "react-redux";
import { useLocation, useNavigate } from "react-router-dom";
import { useCookies } from "react-cookie";

import { RootState } from "../../redux/_store";
import { setUser, setUserCookieExpiry, UNKNOWN_USER } from "../../redux/AuthSlice";
import { activateSpinner, deactivateSpinner } from "../../redux/SpinnerSlice";

import ColorSelect, { DEFAULT_COLOR } from "../ColorSelect";

import { isGamePackage } from "../../types/game/GamePackage";
import { WWChatPackage } from "../../types/chat/WWChatPackage";
import { isErrorPackage, isReceiveName } from "../../types/game/ClientReceive";
import { RequestName } from "../../types/game/ClientSend";







const TIMEOUT_SECONDS = 60;
const NAME_MIN = 3;
const NAME_MAX = 20;
const VALID_CHARS = 'a-zA-Z0-9_ ';  




function Login({route}: {route: string}) {

  const [cookies, setCookie] = useCookies(['warehouse-wars_user-id', 'warehouse-wars_user-name', 'warehouse-wars_user-expiry']);
  const initialName = cookies.hasOwnProperty('warehouse-wars_user-name') ? cookies['warehouse-wars_user-name'] : '';

  const { user } = useSelector((state: RootState) => state.auth);
  const { netAddr: configs } = useSelector((state: RootState) => state.configs);
  const { shouldConnect } = useSelector((state: RootState) => state.game.socket);

  const dispatch = useDispatch();
  const navigate = useNavigate();
  const location = useLocation();

  const emptyFunc = useCallback<(()=>void)>(()=>{}, []);

  const [text, setText] = useState(initialName);
  const [color, setColor] = useState(DEFAULT_COLOR);
  const [submitEnabled, setSubmitEnabled] = useState(false);
  const [textEnabled, setTextEnabled] = useState(false);
  const [awaitingLogin, awaitLogin] = useState(false);
  const [invalidUsernames, setInvalidUsernames] = useState<string[]>([]);

  const touched = useRef(false);
  const awaitLoginFunction = useRef<(()=>void)>(emptyFunc);
  const awaitLoginExpiry = useRef<Date>(new Date());
  const awaitToken = useRef('');
  const loginTimeout = useRef<NodeJS.Timeout|number|null>(null);
  
  const invalidMessage: string = `A valid name should be between ${NAME_MIN} and ${NAME_MAX} characters long, \nand should be composed of only letters, numbers, underscore, and space.`;
  const currentPattern: string = `((?!^(${invalidUsernames.join('|')})$)[${VALID_CHARS}]{${NAME_MIN},${NAME_MAX}})`;
  const match = text.match(new RegExp(currentPattern,'g'));
  const isValid: boolean = (match !== null && match[0] ===  text);

  



  const getAddr = useCallback(async () => {
    return `ws://${configs.address}:${configs.port}/ww`;
  }, [configs]);

  const {
    sendMessage,
    readyState,
  } = 
  useWebSocket(getAddr, {
    share: true,
    filter: (message: MessageEvent<any>) => {
      if (typeof message.data === 'string'){
        let json;
        try{
          json = JSON.parse(message.data);
        }
        catch (err){ return false; }
        if (isGamePackage(json))
          return true;
      }
      else if (typeof message.data === 'object'){
        if (isGamePackage(message.data))
          return true;
      }
      return false;
    },
    onMessage: (event: MessageEvent<any>) => {
      if (typeof event.data === 'string'){
        let json;
        try{
          json = JSON.parse(event.data);
        }
        catch (err){ return false; }
        handlePack(json);
      }
      else if (typeof event.data === 'object'){
        handlePack(event.data);
      }
    },
  }, shouldConnect);

  function handlePack(pack: WWChatPackage){
    //console.log(`awaitingLogin: ${awaitingLogin}\npack.token: ${pack.token}\nawaitToken: ${awaitToken.current}`);
    if (!awaitingLogin || (pack.hasOwnProperty('token') && pack.token !== awaitToken.current))
      return;
    if (isReceiveName(pack)){
      if (!pack.id){ //invalid name, update pattern
        awaitToken.current = '';
        awaitLogin(false);
        dispatch(deactivateSpinner());
        alert(`username ${pack.name} already exists, please choose another name`);
        setSubmitEnabled(true);
        setTextEnabled(true);
        setInvalidUsernames([pack.name, ...invalidUsernames]);
        return;
      }
      dispatch(setUser({id: pack.id, name: pack.name, color: color}));
      dispatch(setUserCookieExpiry(pack.expiry));
      setCookie('warehouse-wars_user-expiry', pack.expiry, {sameSite: 'strict'});
      setCookie('warehouse-wars_user-id', pack.id, {expires: new Date(pack.expiry), sameSite: 'strict'});
      setCookie('warehouse-wars_user-name', pack.name, {expires: new Date(pack.expiry),  sameSite: 'strict'});
      dispatch(deactivateSpinner());
      awaitToken.current = '';
      awaitLogin(false);
      if (loginTimeout.current !== null)
        clearTimeout(loginTimeout.current);
      navigate('/lobby', {state: {from: location.pathname}});
    }
    else if(isErrorPackage(pack)){
      console.log(`error: ${pack.message}`);
      loginTimeout.current = null;
      awaitLogin(false);
      setSubmitEnabled(true);
      setTextEnabled(true);
      dispatch(deactivateSpinner());
      alert(`An error occurred: ${pack.message}`);
    }
  }




  function submit (e: SyntheticEvent) {
    e.preventDefault();

    if (!text || text===''){
      alert('Username required');
      return;
    }
    else if (!isValid){
      alert(`Username invalid.\n${invalidMessage}`);
      return;
    }
    else if (readyState !== ReadyState.OPEN){
      alert('Websocket not open');
      return;
    }

    let pack: RequestName = {type: 'request_name', name: text};
    let id = cookies["warehouse-wars_user-id"] ?? '';
    let _expiry = cookies["warehouse-wars_user-expiry"] ?? '';
    let expiry = _expiry === '' ? -1 : new Date(_expiry).getTime();
    if (id !== '' && expiry > Date.now() )
      pack['id'] = id;
    awaitToken.current = (user?.id ?? UNKNOWN_USER)+"_"+Date.now();
    pack.token  = awaitToken.current;

    setSubmitEnabled(false);
    setTextEnabled(false);
    dispatch(activateSpinner('Logging in...'));
    if (loginTimeout.current !== null){
      clearTimeout(loginTimeout.current);
    }
    awaitLoginExpiry.current = new Date(Date.now() + (TIMEOUT_SECONDS * 1000));
    awaitLoginFunction.current = () => {
      loginTimeout.current = null;
      console.log('!! login timed out'); 
      dispatch(deactivateSpinner());
      awaitLogin(false);
      setSubmitEnabled(true);
      setTextEnabled(true);
      alert('Could not log in, request timed out!');
    };
    //loginTimeout.current = setTimeout(awaitLoginFunction.current, awaitLoginExpiry.current.getTime() - Date.now());
    awaitLogin(true);
    sendMessage(JSON.stringify(pack));
  }


  useMemo(()=>{
    if (awaitingLogin){
      let time = awaitLoginExpiry.current.getTime() - Date.now();
      console.log(`creating new login timeout set to ${time}ms`);
      loginTimeout.current = setTimeout(awaitLoginFunction.current, time);
    }
    else if (!awaitingLogin) {
      if (loginTimeout.current !== null){
        clearTimeout(loginTimeout.current);
        loginTimeout.current = null;
        console.log(`destroying login timeout`);
      }
      awaitLoginFunction.current = emptyFunc;
      awaitLoginExpiry.current = new Date();
    }
  }, [awaitingLogin]);

  

  
  useEffect(() => {
    console.log(`Login component at "/${route}"`);

    return () => {
      console.log('Login component unmounting');

      if (loginTimeout.current !== null){
        clearTimeout(loginTimeout.current);
        loginTimeout.current = null;
        console.log(`destroying login timeout on login unmount`);
      }
    }
  }, []);

  useEffect(() => {
    if (readyState === ReadyState.OPEN){
      setSubmitEnabled(true);
      setTextEnabled(true);
    }
  }, [readyState]);



  return (
    <>
      <form onSubmit={submit}> 
          <label htmlFor="request_name">Display Name:</label>
          <div className="input-container">
              <input type="text" 
                id="request_name"
                placeholder="Enter username"
                value={text}
                disabled={!textEnabled}
                required={true}
                pattern={currentPattern}
                onChange={(e) => {
                  setText(e.target.value);
                  if (!touched.current)
                    touched.current = true;
                  const match = e.target.value.match(new RegExp(currentPattern,'g'));
                  const valid = (match !== null && match[0] ===  e.target.value);
                  if (valid && !submitEnabled)
                    setSubmitEnabled(true);
                  else if (!valid && submitEnabled)
                    setSubmitEnabled(false);
                }} />
              <input type="submit" value={"Login"} disabled={!submitEnabled}/>
          </div>
          {!isValid && touched.current && (<div className="invalid_input">{invalidMessage}</div>)}
          {invalidUsernames.length > 0 && 
            <div className="invalid_input">
              <u>Invalid usernames attempted</u>
              { invalidUsernames.map((name, index) => (<p key={index}>{name}</p>) ) }
            </div>
          }
            
          <label>Color</label>
          <div className="input-container">
            <ColorSelect selectedColor={color} setColor={setColor}/>
          </div>
          <br/>
      </form>
    </>
  )
}

export default Login

// JavaScriptProjects/AngularProjects/warehouse_wars/front-end/ww-angular/src/app/components/login/login.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { FormBuilder, FormGroup, FormControl, Validators } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';
import { Observable, Subscription } from 'rxjs';

import { ClientService } from 'src/app/services/game/client/client.service';
import { isErrorPackage, isReceiveName } from 'src/app/types/ClientReceive';
import { RequestName } from 'src/app/types/ClientSend';
import { WWUserProfile } from 'src/app/types/WWUser';
import { UserProfile } from 'src/app/types/User';
import { Color } from 'src/app/types/Color';



const TIMEOUT_SECONDS = 60;
const NAME_MIN = 3;
const NAME_MAX = 20;



@Component({
  selector: 'ww-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit, OnDestroy {
  loginForm: FormGroup;

  defaultColor: string = '#999999';
  selectedColor: string = this.defaultColor;
  colors: Color[] = [{name:"default", value:this.defaultColor}, {name:'custom', value:this.selectedColor}];

  colorsObs?: Observable<Color[]>;
  private colorTextFilePath: string = "assets/colors.json";

  validChars = 'a-zA-Z0-9_ ';
  private invalidMessage: string = `A valid name should be between ${NAME_MIN} and ${NAME_MAX} characters long, \nand should be composed of only letters, numbers, underscore, and space.`;
  invalidNameMessage: string = this.invalidMessage;
  invalidName: boolean = true;

  
  invalidUsernames: string[] = [];
  currentPattern: string = `((?!^(${this.invalidUsernames.join('|')})$)[${this.validChars}]+)`;
  patternInvalidator = Validators.pattern(this.currentPattern);

  awaitingLogin: boolean = false;
  awaitToken: string | undefined; //undefined since it isn't a JsonElement
  private loginTimeout: NodeJS.Timeout | null = null;
  
  private subscriptions: Subscription[] = [];



  constructor (private router: Router, private client: ClientService, private http: HttpClient, 
    private formBuilder: FormBuilder, private user: UserProfile /*injected as WWUserProfile*/) 
  {
    this.loginForm = this.formBuilder.group({
      requestName: new FormControl({ value: this.client.getNameCookie(), disabled: true }),
      loginSubmit: new FormControl({ value: 'Send', disabled: true }),

      colorGroup: new FormGroup({
        colorSelectControl: new FormControl(this.colors[0].value),
        colorCustomControl: new FormControl(this.selectedColor)
      })
    });

    this.colorsObs = this.http.get<Color[]>(this.colorTextFilePath, {responseType: 'json'});
  }



  ngOnDestroy() {
    if (this.loginTimeout !== null)
      clearTimeout(this.loginTimeout);
    for (let sub of this.subscriptions){
      sub.unsubscribe();
    }
    this.subscriptions = [];
    this.client.onFinishedWaiting();
  }



  ngOnInit (){
    this.setDefaults();
    let subscription: Subscription;

    this.loginForm.controls['requestName'].setValidators([
      Validators.minLength(NAME_MIN), Validators.maxLength(NAME_MAX), 
      Validators.required, Validators.pattern(`^[${this.validChars}]+$`)] );
    this.loginForm.controls['requestName'].updateValueAndValidity();

    if (this.loginForm.controls['requestName'].invalid && this.loginForm.controls['loginSubmit'].enabled)
      this.loginForm.controls['loginSubmit'].disable();


    //component is destroyed on route change
    //this.client.pathObservable.subscribe(pEnum => { this.setDefaults(); });


    subscription = this.client.auth.subscribe(authorized => {
      if (authorized)   return;
      let expiryMessage = `UserId cookie expired\nid: [${this.user.id}]\npath: ${this.router.url}`;
      console.log(expiryMessage);
      //alert(expiryMessage);
      //this.router.navigate(['login']);
    });
    this.subscriptions.push(subscription);


    subscription = this.loginForm.controls['requestName'].valueChanges.subscribe(change => {
      this.invalidName = this.loginForm.controls['requestName'].invalid;
      if (this.loginForm.controls['requestName'].invalid){
        let name: string = this.loginForm.controls['requestName'].value;
        let chars = [...new Set(name.replace(RegExp(`[${this.validChars}]`, 'g'),'').split(''))];
        let invalidChars = chars.length > 0;
        let invalidLength = name.length < NAME_MIN || name.length > NAME_MAX;
        if (invalidChars || invalidLength)
          this.invalidNameMessage = `${this.invalidMessage}\n${invalidLength ? '\n- invalid length ('+name.length+')' : ''}${invalidChars ? '\n- invalid characters:  '+chars.join('') : ''}`;
      }
      if (this.loginForm.controls['requestName'].invalid && this.loginForm.controls['loginSubmit'].enabled)
        this.loginForm.controls['loginSubmit'].disable();
      else if (this.loginForm.controls['requestName'].valid && this.loginForm.controls['loginSubmit'].disabled)
        this.loginForm.controls['loginSubmit'].enable();
    });
    this.subscriptions.push(subscription);
    

    subscription = this.client.socketIsOpenObservable.subscribe((isOpen)=>{
      isOpen ? this.enable() : this.disable();
      if (!isOpen){
        this.setDefaults();
        this.client.onFinishedWaiting();
      }
    });
    this.subscriptions.push(subscription);


    subscription = this.client.packObservable.subscribe(pack => {
      if (!this.awaitingLogin
      || (pack.hasOwnProperty('token') && this.awaitToken !== pack.token))
        return;
      if (isReceiveName(pack)){
        if (!pack.id){ //update invalid name pattern
          if (this.invalidUsernames.length > 0)
            this.loginForm.controls['requestName'].removeValidators(this.patternInvalidator);
          this.invalidUsernames.push(pack.name);
          this.currentPattern = `((?!^(${this.invalidUsernames.join('|')})$)[${this.validChars}]+)`;
          console.log(`new invalidating pattern ::   ${this.currentPattern}`);
          this.patternInvalidator = Validators.pattern(this.currentPattern);
          this.loginForm.controls['requestName'].addValidators(this.patternInvalidator);
          this.loginForm.controls['requestName'].updateValueAndValidity();
          this.awaitingLogin = false;
          this.awaitToken = undefined;
          this.client.onFinishedWaiting();
          this.enable();
          alert(`username ${pack.name} already exists, please choose another name`);
          return;
        }
        this.user.id = pack.id;
        this.user.name = pack.name;
        //this.user.color = this.selectedColor;
        try{
          (this.user as WWUserProfile).color = this.selectedColor; //because WWUserProfile is injected as UserProfile
        }
        catch (err) {console.error(err);}
        this.user.emitProfileUpdate();
        this.client.setAuth(this.user.getUser(), new Date(pack.expiry));
        this.awaitingLogin = false;
        this.awaitToken = undefined;
        this.client.onFinishedWaiting();
        this.router.navigate(['lobby']);
      }
      else if(isErrorPackage(pack)){
        console.log(`error: ${pack.message}`);
        this.awaitingLogin = false;
        this.awaitToken = undefined;
        this.enable();
        this.client.onFinishedWaiting();
        alert(`An error occurred: ${pack.message}`);
      }
    });
    this.subscriptions.push(subscription);
  }



  setDefaults (){
    this.awaitingLogin = false;
    this.awaitToken = undefined;
    if (this.loginTimeout !== null)
      clearTimeout(this.loginTimeout);
    this.loginTimeout = null;
    this.loginForm.controls['requestName'].patchValue(this.client.getNameCookie());
    this.loginForm.controls['requestName'].updateValueAndValidity();
    this.invalidName = this.loginForm.controls['requestName'].invalid;
  }


  enable (){
    this.loginForm.controls['requestName'].enable();
    this.loginForm.controls['loginSubmit'].enable();
  }
  disable () {
    this.loginForm.controls['requestName'].disable();
    this.loginForm.controls['loginSubmit'].disable();
  }





  login (){
    let pack: RequestName = {type: 'request_name', name: this.loginForm.controls['requestName'].value};
    let id;
    if ((id = this.client.getIdCookie()) !== '' && !this.client.cookieIsExpired())
      pack['id'] = id;
    this.awaitingLogin = true;
    this.awaitToken = this.user.id +'_'+ Date.now();
    pack['token'] = this.awaitToken;
    this.disable();
    this.client.onWaiting('Logging in...');
    this.loginTimeout = setTimeout((_this) => {
      _this.setDefaults();
      _this.enable();
      _this.client.onFinishedWaiting();
      console.log('!! login time out'); 
      alert('Could not log in, request timed out!');
    }, TIMEOUT_SECONDS*1000, this);
    this.client.sendPackage(pack);
  }







  onColorSelect ( event: Event ){
    let element: HTMLSelectElement = (event.target as HTMLSelectElement);
    let oldColor = this.selectedColor;
    this.selectedColor = element.value;
    this.loginForm.controls['colorGroup'].patchValue({'colorCustomControl': element.value});
    console.log(`change color from ${oldColor} to ${this.selectedColor}`);
  }

  onColorCustom (event: Event){
    let element: HTMLInputElement = (event.target as HTMLInputElement);
    let oldColor = this.selectedColor;
    this.selectedColor = element.value;
    this.colors[1].value = element.value;
    this.loginForm.controls['colorGroup'].patchValue({'colorSelectControl': this.colors[1].value});
    console.log(`custom change color from ${oldColor} to ${this.selectedColor}`);
  }
}
